services:
  # 1. API Gateway + Microservices (Unified Container)
  - type: web
    name: nexus-gateway
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: USER1_TARGET
        value: http://127.0.0.1:4001
      - key: USER2_TARGET
        value: http://127.0.0.1:4003
      - key: ORDER_TARGET
        value: http://127.0.0.1:4002
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false

  # 2. Pub/Sub Broker Relay
  - type: web
    name: nexus-pubsub
    env: docker
    dockerContext: .
    dockerfilePath: ./pubsub/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        sync: false
